// 20 ready-made starter templates organized by subject and grade level.
// Each template = a multi-poll lesson activity.
// Used by TemplateGalleryModal to one-click create polls in an event.

export const STARTER_TEMPLATES = [
  // ─── Математика ──────────────────────────────────────────────
  {
    id: 'math-fractions-elementary',
    title: 'Дропки — основни поими',
    subject: 'Математика',
    grade: 'Основно (5-6 одд.)',
    icon: '🔢',
    color: 'from-blue-500 to-cyan-500',
    description: 'Краток квиз за разбирање на дропки — собирање, споредба и претворање.',
    polls: [
      {
        question: 'Што е дропка?',
        type: 'poll', is_quiz: false,
        options: [
          { text: 'Број што претставува дел од целина', is_correct: false },
          { text: 'Само цел број', is_correct: false },
          { text: 'Знак за множење', is_correct: false },
        ],
      },
      {
        question: 'Колку е 1/2 + 1/4?',
        type: 'quiz', is_quiz: true,
        options: [
          { text: '2/6', is_correct: false },
          { text: '3/4', is_correct: true },
          { text: '1/6', is_correct: false },
          { text: '2/4', is_correct: false },
        ],
      },
      {
        question: 'Која е поголема: 3/5 или 4/7?',
        type: 'quiz', is_quiz: true,
        options: [
          { text: '3/5', is_correct: true },
          { text: '4/7', is_correct: false },
          { text: 'Еднакви се', is_correct: false },
        ],
      },
    ],
  },
  {
    id: 'math-pythagoras',
    title: 'Питагорова теорема',
    subject: 'Математика',
    grade: 'Средно',
    icon: '📐',
    color: 'from-blue-500 to-indigo-500',
    description: 'Примена на Питагорова теорема со 4 прашања.',
    polls: [
      { question: 'Што гласи Питагоровата теорема?', type: 'poll', is_quiz: false,
        options: [{ text: 'a² + b² = c²' }, { text: 'a + b = c' }, { text: 'a × b = c' }] },
      { question: 'Ако катетите се 3 и 4, колку е хипотенузата?', type: 'quiz', is_quiz: true,
        options: [{ text: '5', is_correct: true }, { text: '7', is_correct: false }, { text: '12', is_correct: false }, { text: '6', is_correct: false }] },
      { question: 'Колку ти беше јасна оваа лекција?', type: 'rating', is_quiz: false, options: [] },
    ],
  },
  {
    id: 'math-percentages',
    title: 'Проценти во секојдневието',
    subject: 'Математика',
    grade: 'Основно (7-8 одд.)',
    icon: '📊',
    color: 'from-purple-500 to-pink-500',
    description: 'Пресметка на попусти, ДДВ и проценти.',
    polls: [
      { question: '20% од 150 е?', type: 'quiz', is_quiz: true,
        options: [{ text: '30', is_correct: true }, { text: '20', is_correct: false }, { text: '50', is_correct: false }, { text: '15', is_correct: false }] },
      { question: 'Цена 800 ден. со попуст 25%, плаќаш?', type: 'quiz', is_quiz: true,
        options: [{ text: '600', is_correct: true }, { text: '775', is_correct: false }, { text: '400', is_correct: false }] },
    ],
  },

  // ─── Информатика ─────────────────────────────────────────────
  {
    id: 'cs-html-basics',
    title: 'HTML — основни ознаки',
    subject: 'Информатика',
    grade: 'Средно',
    icon: '💻',
    color: 'from-orange-500 to-red-500',
    description: 'Препознавање на HTML елементи и нивна функција.',
    polls: [
      { question: 'Која ознака е за наслов?', type: 'quiz', is_quiz: true,
        options: [{ text: '<h1>', is_correct: true }, { text: '<p>', is_correct: false }, { text: '<title>', is_correct: false }, { text: '<head>', is_correct: false }] },
      { question: 'За што служи <a href="...">?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Линк', is_correct: true }, { text: 'Слика', is_correct: false }, { text: 'Параграф', is_correct: false }] },
      { question: 'Со еден збор: што мислиш за веб дизајн?', type: 'wordcloud', is_quiz: false, options: [] },
    ],
  },
  {
    id: 'cs-algorithms',
    title: 'Алгоритми — впишување',
    subject: 'Информатика',
    grade: 'Средно',
    icon: '⚙️',
    color: 'from-emerald-500 to-teal-500',
    description: 'Концепти на алгоритамско размислување.',
    polls: [
      { question: 'Што е алгоритам?', type: 'poll', is_quiz: false,
        options: [{ text: 'Низа на чекори за решавање проблем' }, { text: 'Програмски јазик' }, { text: 'Само математичка формула' }] },
      { question: 'Која е сложеноста на бинарно пребарување?', type: 'quiz', is_quiz: true,
        options: [{ text: 'O(log n)', is_correct: true }, { text: 'O(n)', is_correct: false }, { text: 'O(n²)', is_correct: false }] },
    ],
  },
  {
    id: 'cs-internet-safety',
    title: 'Интернет безбедност',
    subject: 'Информатика',
    grade: 'Основно',
    icon: '🛡️',
    color: 'from-red-500 to-rose-500',
    description: 'Како да се заштитиш онлајн.',
    polls: [
      { question: 'Дали смееш да делиш лозинка со друг?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Никогаш', is_correct: true }, { text: 'Само со пријатели', is_correct: false }, { text: 'Секогаш', is_correct: false }] },
      { question: 'Со еден збор: што е најголема онлајн закана?', type: 'wordcloud', is_quiz: false, options: [] },
    ],
  },

  // ─── Англиски јазик ──────────────────────────────────────────
  {
    id: 'eng-tenses',
    title: 'English Tenses Review',
    subject: 'Англиски',
    grade: 'Средно',
    icon: '🇬🇧',
    color: 'from-indigo-500 to-purple-500',
    description: 'Present Simple vs Present Continuous and more.',
    polls: [
      { question: 'I ___ to school every day.', type: 'quiz', is_quiz: true,
        options: [{ text: 'go', is_correct: true }, { text: 'going', is_correct: false }, { text: 'goes', is_correct: false }, { text: 'went', is_correct: false }] },
      { question: 'Look! The bus ___.', type: 'quiz', is_quiz: true,
        options: [{ text: 'is coming', is_correct: true }, { text: 'comes', is_correct: false }, { text: 'come', is_correct: false }] },
      { question: 'How confident are you with English tenses?', type: 'rating', is_quiz: false, options: [] },
    ],
  },
  {
    id: 'eng-vocabulary',
    title: 'Vocabulary — Daily Life',
    subject: 'Англиски',
    grade: 'Основно',
    icon: '🗣️',
    color: 'from-pink-500 to-rose-500',
    description: 'Common words and synonyms.',
    polls: [
      { question: 'What does "happy" mean?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Sad', is_correct: false }, { text: 'Joyful', is_correct: true }, { text: 'Tired', is_correct: false }] },
      { question: 'In one word: how is your day?', type: 'wordcloud', is_quiz: false, options: [] },
    ],
  },

  // ─── Природни науки ──────────────────────────────────────────
  {
    id: 'sci-solar-system',
    title: 'Сончев систем',
    subject: 'Природни науки',
    grade: 'Основно',
    icon: '🪐',
    color: 'from-violet-500 to-purple-500',
    description: 'Планети, ѕвезди и распоред.',
    polls: [
      { question: 'Колку планети има во Сончевиот систем?', type: 'quiz', is_quiz: true,
        options: [{ text: '7', is_correct: false }, { text: '8', is_correct: true }, { text: '9', is_correct: false }] },
      { question: 'Која е најголема планета?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Земја', is_correct: false }, { text: 'Јупитер', is_correct: true }, { text: 'Сатурн', is_correct: false }, { text: 'Марс', is_correct: false }] },
    ],
  },
  {
    id: 'sci-photosynthesis',
    title: 'Фотосинтеза',
    subject: 'Биологија',
    grade: 'Основно (8 одд.)',
    icon: '🌱',
    color: 'from-green-500 to-emerald-500',
    description: 'Процес на фотосинтеза кај растенијата.',
    polls: [
      { question: 'Што е потребно за фотосинтеза?', type: 'poll', is_quiz: false,
        options: [{ text: 'Сонце, вода, CO₂' }, { text: 'Само вода' }, { text: 'Само сонце' }] },
      { question: 'Кои организми вршат фотосинтеза?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Растенија', is_correct: true }, { text: 'Луѓе', is_correct: false }, { text: 'Габи', is_correct: false }] },
    ],
  },
  {
    id: 'sci-states-of-matter',
    title: 'Состојби на материјата',
    subject: 'Физика',
    grade: 'Основно',
    icon: '💧',
    color: 'from-cyan-500 to-blue-500',
    description: 'Цврста, течна, гасовита и плазма.',
    polls: [
      { question: 'Колку основни состојби на материјата постојат?', type: 'quiz', is_quiz: true,
        options: [{ text: '3', is_correct: false }, { text: '4', is_correct: true }, { text: '5', is_correct: false }] },
      { question: 'Со еден збор: пример за гас', type: 'wordcloud', is_quiz: false, options: [] },
    ],
  },

  // ─── Историја и Географија ───────────────────────────────────
  {
    id: 'hist-mk-independence',
    title: 'Независност на Македонија',
    subject: 'Историја',
    grade: 'Средно',
    icon: '🇲🇰',
    color: 'from-red-600 to-yellow-500',
    description: 'Клучни датуми и личности.',
    polls: [
      { question: 'Која година Македонија се прогласи независна?', type: 'quiz', is_quiz: true,
        options: [{ text: '1991', is_correct: true }, { text: '1989', is_correct: false }, { text: '1995', is_correct: false }, { text: '2001', is_correct: false }] },
      { question: 'Кога се одржа референдумот за независност?', type: 'quiz', is_quiz: true,
        options: [{ text: '8 септември 1991', is_correct: true }, { text: '2 август 1944', is_correct: false }, { text: '17 ноември 1991', is_correct: false }] },
    ],
  },
  {
    id: 'geo-world-capitals',
    title: 'Главни градови во светот',
    subject: 'Географија',
    grade: 'Основно',
    icon: '🗺️',
    color: 'from-amber-500 to-orange-500',
    description: 'Препознавање на главни градови.',
    polls: [
      { question: 'Главен град на Франција?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Париз', is_correct: true }, { text: 'Лион', is_correct: false }, { text: 'Марсеј', is_correct: false }] },
      { question: 'Главен град на Јапонија?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Токио', is_correct: true }, { text: 'Осака', is_correct: false }, { text: 'Кјото', is_correct: false }] },
      { question: 'Главен град на Австралија?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Канбера', is_correct: true }, { text: 'Сиднеј', is_correct: false }, { text: 'Мелбурн', is_correct: false }] },
    ],
  },

  // ─── Македонски јазик ────────────────────────────────────────
  {
    id: 'mk-grammar-padeji',
    title: 'Македонска граматика — падежи',
    subject: 'Македонски',
    grade: 'Основно',
    icon: '📖',
    color: 'from-rose-500 to-pink-500',
    description: 'Падежи во македонскиот јазик.',
    polls: [
      { question: 'Колку падежи има во современиот македонски јазик?', type: 'quiz', is_quiz: true,
        options: [{ text: '0 (исчезнале)', is_correct: true }, { text: '7', is_correct: false }, { text: '3', is_correct: false }] },
      { question: 'Со еден збор: омилен македонски писател', type: 'wordcloud', is_quiz: false, options: [] },
    ],
  },
  {
    id: 'mk-literature',
    title: 'Македонски писатели',
    subject: 'Македонски',
    grade: 'Средно',
    icon: '✍️',
    color: 'from-fuchsia-500 to-purple-500',
    description: 'Препознавање на класични дела.',
    polls: [
      { question: 'Кој ја напиша „Бели мугри"?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Кочо Рацин', is_correct: true }, { text: 'Блаже Конески', is_correct: false }, { text: 'Григор Прличев', is_correct: false }] },
      { question: 'Кој е автор на „Сердарот"?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Григор Прличев', is_correct: true }, { text: 'Кочо Рацин', is_correct: false }, { text: 'Славко Јаневски', is_correct: false }] },
    ],
  },

  // ─── Корпоративни / Обуки ────────────────────────────────────
  {
    id: 'biz-icebreaker',
    title: 'Icebreaker — нов тим',
    subject: 'Бизнис',
    grade: 'Обука',
    icon: '🤝',
    color: 'from-sky-500 to-blue-500',
    description: 'Запознавање на тим преку забавни прашања.',
    polls: [
      { question: 'Со еден збор: како се чувствуваш денес?', type: 'wordcloud', is_quiz: false, options: [] },
      { question: 'Каде би сакал/а да си на одмор?', type: 'poll', is_quiz: false,
        options: [{ text: 'Плажа' }, { text: 'Планина' }, { text: 'Град' }, { text: 'Дома' }] },
      { question: 'Колку години работно искуство имаш?', type: 'rating', is_quiz: false, options: [] },
    ],
  },
  {
    id: 'biz-workshop-feedback',
    title: 'Feedback по обука',
    subject: 'Бизнис',
    grade: 'Обука',
    icon: '📝',
    color: 'from-teal-500 to-cyan-500',
    description: 'Краток feedback по работилница.',
    polls: [
      { question: 'Колку корисна беше обуката?', type: 'rating', is_quiz: false, options: [] },
      { question: 'Што најмногу ти се допадна?', type: 'open', is_quiz: false, options: [] },
      { question: 'Што би подобрил/а?', type: 'open', is_quiz: false, options: [] },
    ],
  },

  // ─── Универзитет ─────────────────────────────────────────────
  {
    id: 'uni-exit-ticket',
    title: 'Exit Ticket — крај на час',
    subject: 'Универзитет',
    grade: 'Високо',
    icon: '🎓',
    color: 'from-indigo-600 to-violet-600',
    description: 'Брза проверка на знаење на крај на предавање.',
    polls: [
      { question: 'Колку ти беше јасна темата?', type: 'rating', is_quiz: false, options: [] },
      { question: 'Една работа што ја научи денес:', type: 'open', is_quiz: false, options: [] },
      { question: 'Едно прашање што го имаш:', type: 'open', is_quiz: false, options: [] },
    ],
  },
  {
    id: 'uni-debate',
    title: 'Дебата — за и против',
    subject: 'Универзитет',
    grade: 'Високо',
    icon: '⚖️',
    color: 'from-yellow-500 to-amber-500',
    description: 'Поларизирачко прашање за дискусија.',
    polls: [
      { question: 'AI ќе ги замени наставниците за 20 години?', type: 'poll', is_quiz: false,
        options: [{ text: 'Сосема се согласувам' }, { text: 'Делумно се согласувам' }, { text: 'Не се согласувам' }, { text: 'Воопшто не се согласувам' }] },
      { question: 'Со еден збор: твојот аргумент', type: 'wordcloud', is_quiz: false, options: [] },
    ],
  },

  // ─── Математика — Прошир. ────────────────────────────────────
  {
    id: 'math-linear-equations',
    title: 'Линеарни равенки',
    subject: 'Математика',
    grade: 'Основно (8-9 одд.)',
    icon: '📏',
    color: 'from-blue-600 to-violet-500',
    description: 'Равенки од видот ax + b = c.',
    polls: [
      { question: 'Реши: 2x + 5 = 13', type: 'quiz', is_quiz: true,
        options: [{ text: 'x = 4', is_correct: true }, { text: 'x = 9', is_correct: false }, { text: 'x = 6', is_correct: false }, { text: 'x = 3', is_correct: false }] },
      { question: 'Реши: 3(x − 2) = 9', type: 'quiz', is_quiz: true,
        options: [{ text: 'x = 5', is_correct: true }, { text: 'x = 3', is_correct: false }, { text: 'x = 1', is_correct: false }] },
      { question: 'Со еден збор: што е равенка?', type: 'wordcloud', is_quiz: false, options: [] },
    ],
  },
  {
    id: 'math-quadratic',
    title: 'Квадратни равенки',
    subject: 'Математика',
    grade: 'Средно',
    icon: '🟦',
    color: 'from-indigo-500 to-blue-600',
    description: 'ax² + bx + c = 0 — дискриминанта и корени.',
    polls: [
      { question: 'Колку решенија има x² − 4 = 0?', type: 'quiz', is_quiz: true,
        options: [{ text: '2 (x = ±2)', is_correct: true }, { text: '1 (x = 2)', is_correct: false }, { text: '0', is_correct: false }] },
      { question: 'Дискриминантата D = b² − 4ac. Ако D < 0, тогаш:', type: 'quiz', is_quiz: true,
        options: [{ text: 'Нема реални решенија', is_correct: true }, { text: 'Има 2 реални', is_correct: false }, { text: 'Има 1 реално', is_correct: false }] },
      { question: 'Реши: x² − 5x + 6 = 0', type: 'quiz', is_quiz: true,
        options: [{ text: 'x = 2 или x = 3', is_correct: true }, { text: 'x = 1 или x = 6', is_correct: false }, { text: 'x = −2 или x = −3', is_correct: false }] },
    ],
  },
  {
    id: 'math-functions',
    title: 'Линеарна функција',
    subject: 'Математика',
    grade: 'Средно',
    icon: '📈',
    color: 'from-cyan-500 to-blue-500',
    description: 'f(x) = kx + n — наклон и пресек.',
    polls: [
      { question: 'За f(x) = 2x + 3, колку е f(4)?', type: 'quiz', is_quiz: true,
        options: [{ text: '11', is_correct: true }, { text: '14', is_correct: false }, { text: '8', is_correct: false }, { text: '7', is_correct: false }] },
      { question: 'Кој е наклонот на y = −3x + 7?', type: 'quiz', is_quiz: true,
        options: [{ text: '−3', is_correct: true }, { text: '7', is_correct: false }, { text: '3', is_correct: false }] },
    ],
  },
  {
    id: 'math-trigonometry',
    title: 'Тригонометрија — основи',
    subject: 'Математика',
    grade: 'Средно',
    icon: '📐',
    color: 'from-purple-600 to-indigo-600',
    description: 'sin, cos, tan и единичен круг.',
    polls: [
      { question: 'Колку е sin(30°)?', type: 'quiz', is_quiz: true,
        options: [{ text: '1/2', is_correct: true }, { text: '√2/2', is_correct: false }, { text: '√3/2', is_correct: false }, { text: '1', is_correct: false }] },
      { question: 'Колку е cos(60°)?', type: 'quiz', is_quiz: true,
        options: [{ text: '1/2', is_correct: true }, { text: '0', is_correct: false }, { text: '√3/2', is_correct: false }] },
      { question: 'Идентитет: sin²θ + cos²θ = ?', type: 'quiz', is_quiz: true,
        options: [{ text: '1', is_correct: true }, { text: '0', is_correct: false }, { text: 'tanθ', is_correct: false }] },
    ],
  },
  {
    id: 'math-derivatives',
    title: 'Изводи — основи',
    subject: 'Математика',
    grade: 'Средно (4 год.)',
    icon: '∂',
    color: 'from-violet-600 to-purple-600',
    description: 'Правила за диференцирање.',
    polls: [
      { question: 'Изводот на f(x) = x² е:', type: 'quiz', is_quiz: true,
        options: [{ text: '2x', is_correct: true }, { text: 'x', is_correct: false }, { text: 'x²/2', is_correct: false }] },
      { question: 'Изводот на sin(x) е:', type: 'quiz', is_quiz: true,
        options: [{ text: 'cos(x)', is_correct: true }, { text: '−cos(x)', is_correct: false }, { text: '−sin(x)', is_correct: false }] },
      { question: 'Изводот на константа c е:', type: 'quiz', is_quiz: true,
        options: [{ text: '0', is_correct: true }, { text: '1', is_correct: false }, { text: 'c', is_correct: false }] },
    ],
  },
  {
    id: 'math-geometry-area',
    title: 'Плоштина и периметар',
    subject: 'Математика',
    grade: 'Основно (6-7 одд.)',
    icon: '🟥',
    color: 'from-rose-500 to-orange-500',
    description: 'Плоштина и периметар на основни фигури.',
    polls: [
      { question: 'Плоштина на правоаголник 5 × 8 е:', type: 'quiz', is_quiz: true,
        options: [{ text: '40', is_correct: true }, { text: '13', is_correct: false }, { text: '26', is_correct: false }] },
      { question: 'Плоштина на круг со r = 3 (π ≈ 3.14):', type: 'quiz', is_quiz: true,
        options: [{ text: '≈ 28.26', is_correct: true }, { text: '≈ 18.84', is_correct: false }, { text: '≈ 9.42', is_correct: false }] },
      { question: 'Периметар на квадрат со страна 7:', type: 'quiz', is_quiz: true,
        options: [{ text: '28', is_correct: true }, { text: '49', is_correct: false }, { text: '14', is_correct: false }] },
    ],
  },
  {
    id: 'math-statistics',
    title: 'Статистика — средна, медијана, мод',
    subject: 'Математика',
    grade: 'Основно (9 одд.)',
    icon: '📊',
    color: 'from-emerald-500 to-cyan-500',
    description: 'Мерки на централна тенденција.',
    polls: [
      { question: 'Аритметичка средина на {2, 4, 6, 8}:', type: 'quiz', is_quiz: true,
        options: [{ text: '5', is_correct: true }, { text: '4', is_correct: false }, { text: '6', is_correct: false }] },
      { question: 'Медијана на {3, 7, 1, 9, 5}:', type: 'quiz', is_quiz: true,
        options: [{ text: '5', is_correct: true }, { text: '7', is_correct: false }, { text: '3', is_correct: false }] },
      { question: 'Мод на {1, 2, 2, 3, 4}:', type: 'quiz', is_quiz: true,
        options: [{ text: '2', is_correct: true }, { text: '3', is_correct: false }, { text: '1', is_correct: false }] },
    ],
  },
  {
    id: 'math-probability',
    title: 'Веројатност — основи',
    subject: 'Математика',
    grade: 'Средно',
    icon: '🎲',
    color: 'from-amber-500 to-rose-500',
    description: 'Класична дефиниција на веројатност.',
    polls: [
      { question: 'Веројатност за паѓање парна на коцка (1–6):', type: 'quiz', is_quiz: true,
        options: [{ text: '1/2', is_correct: true }, { text: '1/3', is_correct: false }, { text: '1/6', is_correct: false }] },
      { question: 'P(A) = 0.7. Колку е P(не A)?', type: 'quiz', is_quiz: true,
        options: [{ text: '0.3', is_correct: true }, { text: '0.7', is_correct: false }, { text: '1', is_correct: false }] },
    ],
  },
  {
    id: 'math-mental-arithmetic',
    title: 'Бројна вештина — менатална математика',
    subject: 'Математика',
    grade: 'Основно',
    icon: '⚡',
    color: 'from-yellow-400 to-orange-500',
    description: 'Брзи пресметки за загревање.',
    polls: [
      { question: '17 × 6 = ?', type: 'quiz', is_quiz: true,
        options: [{ text: '102', is_correct: true }, { text: '112', is_correct: false }, { text: '92', is_correct: false }] },
      { question: '144 ÷ 12 = ?', type: 'quiz', is_quiz: true,
        options: [{ text: '12', is_correct: true }, { text: '14', is_correct: false }, { text: '11', is_correct: false }] },
      { question: '√81 = ?', type: 'quiz', is_quiz: true,
        options: [{ text: '9', is_correct: true }, { text: '8', is_correct: false }, { text: '10', is_correct: false }] },
      { question: '15² = ?', type: 'quiz', is_quiz: true,
        options: [{ text: '225', is_correct: true }, { text: '215', is_correct: false }, { text: '255', is_correct: false }] },
    ],
  },
  {
    id: 'math-logic',
    title: 'Логика и множества',
    subject: 'Математика',
    grade: 'Средно',
    icon: '🧩',
    color: 'from-fuchsia-500 to-violet-500',
    description: 'Основи на математичка логика и множества.',
    polls: [
      { question: 'Ако A = {1,2,3} и B = {2,3,4}, тогаш A ∩ B = ?', type: 'quiz', is_quiz: true,
        options: [{ text: '{2, 3}', is_correct: true }, { text: '{1, 4}', is_correct: false }, { text: '{1, 2, 3, 4}', is_correct: false }] },
      { question: 'A ∪ B за истите множества:', type: 'quiz', is_quiz: true,
        options: [{ text: '{1, 2, 3, 4}', is_correct: true }, { text: '{2, 3}', is_correct: false }, { text: '∅', is_correct: false }] },
      { question: 'p ⇒ q и p е точно. Q?', type: 'quiz', is_quiz: true,
        options: [{ text: 'q е точно', is_correct: true }, { text: 'q е неточно', is_correct: false }, { text: 'не може да се одреди', is_correct: false }] },
    ],
  },
  // ─── Физика / Хемија ─────────────────────────────────────────
  {
    id: 'phy-newton',
    title: 'Њутнови закони',
    subject: 'Физика',
    grade: 'Средно',
    icon: '🍎',
    color: 'from-blue-500 to-slate-700',
    description: 'Трите Њутнови закони на движењето.',
    polls: [
      { question: 'F = ma е израз на:', type: 'quiz', is_quiz: true,
        options: [{ text: 'Втор Њутнов закон', is_correct: true }, { text: 'Прв Њутнов закон', is_correct: false }, { text: 'Закон за гравитација', is_correct: false }] },
      { question: 'Единица за сила во SI:', type: 'quiz', is_quiz: true,
        options: [{ text: 'Њутн (N)', is_correct: true }, { text: 'Џул (J)', is_correct: false }, { text: 'Ват (W)', is_correct: false }] },
    ],
  },
  {
    id: 'chem-periodic-table',
    title: 'Периоден систем — основи',
    subject: 'Физика',
    grade: 'Основно (8-9 одд.)',
    icon: '⚗️',
    color: 'from-emerald-500 to-teal-600',
    description: 'Хемиски елементи и нивни ознаки.',
    polls: [
      { question: 'Која е хемиската ознака за злато?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Au', is_correct: true }, { text: 'Ag', is_correct: false }, { text: 'Go', is_correct: false }] },
      { question: 'H₂O е формула за:', type: 'quiz', is_quiz: true,
        options: [{ text: 'Вода', is_correct: true }, { text: 'Водороден пероксид', is_correct: false }, { text: 'Кислород', is_correct: false }] },
      { question: 'Колку протони има јаглеродот (C)?', type: 'quiz', is_quiz: true,
        options: [{ text: '6', is_correct: true }, { text: '12', is_correct: false }, { text: '8', is_correct: false }] },
    ],
  },
  // ─── Англиски — Прошир. ──────────────────────────────────────
  {
    id: 'eng-conditionals',
    title: 'English Conditionals (If clauses)',
    subject: 'Англиски',
    grade: 'Средно',
    icon: '🔀',
    color: 'from-sky-500 to-indigo-500',
    description: 'Zero, first, second & third conditional.',
    polls: [
      { question: 'If it ___ tomorrow, we will stay home.', type: 'quiz', is_quiz: true,
        options: [{ text: 'rains', is_correct: true }, { text: 'will rain', is_correct: false }, { text: 'rained', is_correct: false }] },
      { question: 'If I ___ rich, I would travel the world.', type: 'quiz', is_quiz: true,
        options: [{ text: 'were', is_correct: true }, { text: 'am', is_correct: false }, { text: 'will be', is_correct: false }] },
    ],
  },
  // ─── Македонски — Прошир. ────────────────────────────────────
  {
    id: 'mk-pravopis',
    title: 'Македонски правопис',
    subject: 'Македонски',
    grade: 'Основно',
    icon: '📝',
    color: 'from-rose-600 to-red-500',
    description: 'Чести правописни прашања.',
    polls: [
      { question: 'Како правилно се пишува?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Не знам', is_correct: true }, { text: 'Незнам', is_correct: false }] },
      { question: 'Која форма е правилна?', type: 'quiz', is_quiz: true,
        options: [{ text: 'ќе одам', is_correct: true }, { text: 'ке одам', is_correct: false }, { text: 'ке-одам', is_correct: false }] },
    ],
  },
  // ─── Историја — Прошир. ──────────────────────────────────────
  {
    id: 'hist-ww2',
    title: 'Втора светска војна',
    subject: 'Историја',
    grade: 'Средно',
    icon: '🕊️',
    color: 'from-slate-600 to-zinc-700',
    description: 'Клучни датуми и настани.',
    polls: [
      { question: 'Кога започна Втората светска војна?', type: 'quiz', is_quiz: true,
        options: [{ text: '1 септември 1939', is_correct: true }, { text: '7 декември 1941', is_correct: false }, { text: '11 ноември 1918', is_correct: false }] },
      { question: 'Кога заврши војната во Европа?', type: 'quiz', is_quiz: true,
        options: [{ text: '8 мај 1945', is_correct: true }, { text: '2 септември 1945', is_correct: false }, { text: '6 јуни 1944', is_correct: false }] },
    ],
  },

  // ─── Општи ───────────────────────────────────────────────────
  {
    id: 'general-quick-quiz',
    title: 'Брз општ квиз',
    subject: 'Општо',
    grade: 'Сите',
    icon: '🧠',
    color: 'from-slate-500 to-zinc-500',
    description: 'Шарен квиз за загревање на мозокот.',
    polls: [
      { question: 'Колку континенти има?', type: 'quiz', is_quiz: true,
        options: [{ text: '5', is_correct: false }, { text: '7', is_correct: true }, { text: '6', is_correct: false }] },
      { question: 'Кој ја насликал Мона Лиза?', type: 'quiz', is_quiz: true,
        options: [{ text: 'Леонардо да Винчи', is_correct: true }, { text: 'Микеланџело', is_correct: false }, { text: 'Пикасо', is_correct: false }] },
      { question: 'Колку ти беше забавно?', type: 'rating', is_quiz: false, options: [] },
    ],
  },
];

export const TEMPLATE_SUBJECTS = [
  'Сите',
  'Математика',
  'Информатика',
  'Англиски',
  'Македонски',
  'Природни науки',
  'Биологија',
  'Физика',
  'Историја',
  'Географија',
  'Бизнис',
  'Универзитет',
  'Општо',
];
